In [52]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [53]:
# Importing the dataset
dataset = pd.read_csv('/content/train.csv', delimiter = ',')

In [54]:
# Cleaning the texts
import re
import nltk

In [55]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []

for i in range(0, 2100):
    review = re.sub('[^a-zA-Z]', ' ', dataset['description_y'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

print(corpus[0:200])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['first trust dj internet idx', 'schwab strateg tr fundament intl larg co index etf', 'vanguard small cap index fund inst', 'duke energi corp new com new isin us c sedol b jz', 'visa inc', 'ford motor co', 'unit st stl cp new', 'vanguard total intl bond index etf', 'schwab us small cap etf', 'mf valu fund cl', 'oppenheim develop mkt fd cl', 'genom health inc com', 'spdr barclay capit intern trea', 'kraft heinz co com', 'vanguard total bond market idx instl pl', 'vanguard interm term invmt grade inv', 'baidu inc spon adr rep', 'novarti ag', 'seaspan corpor cmn', 'vanguard bond index total mkt investor', 'mf municip high cl', 'metlif incorpor', 'vy clarion real estat port srv', 'vanguard short term invest grade', 'spdr p etf iv', 'fund pimco total return admin', 'intel corpor', 'vanguard idx adm', 'paypal hold inco', 'pimco total return fund class r', 'vanguard small cap etf vb', 'nike inc b', 'vanguard institut index fund institut plu share', 'ishar p nation amt free muni', 'pimco total

In [56]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 577)
X = cv.fit_transform(corpus).toarray()

y = dataset.iloc[0:2100, 5].values

In [57]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [58]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [59]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [60]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix for Naive Bayes is : ")
print(cm)

Confusion matrix for Naive Bayes is : 
[[ 91  14]
 [ 79 236]]


In [61]:
from sklearn.metrics import accuracy_score

# Naive Bayes accuracy
nb_accuracy = accuracy_score(y_test, y_pred)
print("Accuracy for Naive Bayes: ", nb_accuracy)

Accuracy for Naive Bayes:  0.7785714285714286


In [62]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 0)
classifier1.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [63]:
# Predicting the Test set results
y_predL = classifier1.predict(X_test)

In [64]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_predL)
print("Confusion matrix for Logistic regression is : ")
print(cm1)

Confusion matrix for Logistic regression is : 
[[ 74  31]
 [ 15 300]]


In [65]:
# Logistic Regression accuracy
lr_accuracy = accuracy_score(y_test, y_predL)
print("Accuracy for Logistic Regression: ", lr_accuracy)

Accuracy for Logistic Regression:  0.8904761904761904


In [66]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier2.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [67]:
# Predicting the Test set results
y_predD = classifier2.predict(X_test)

In [68]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, y_predD)
print("Confusion matrix for Decision tree is is : ")
print(cm2)

Confusion matrix for Decision tree is is : 
[[ 86  19]
 [ 25 290]]


In [69]:
# Decision Tree accuracy
dt_accuracy = accuracy_score(y_test, y_predD)
print("Accuracy for Decision Tree: ", dt_accuracy)

Accuracy for Decision Tree:  0.8952380952380953


In [70]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier3.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [71]:

# Predicting the Test set results
y_predR = classifier3.predict(X_test)

In [72]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test, y_predR)
print("Confusion matrix for Random Forest  is : ")
print(cm3)

Confusion matrix for Random Forest  is : 
[[ 80  25]
 [ 18 297]]


In [73]:
# Random Forest accuracy
rf_accuracy = accuracy_score(y_test, y_predR)
print("Accuracy for Random Forest: ", rf_accuracy)

Accuracy for Random Forest:  0.8976190476190476


In [74]:
#***************************** Prediction of text dataset with random forest************
# as random forest is best for prediction we have to process descrption y of test dataset.
# and pass this corpus to Random Forest classifier

Tdataset = pd.read_csv('/content/test.csv', delimiter = ',')

In [76]:
# ltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 516):
    review = re.sub('[^a-zA-Z]', ' ', Tdataset['description_y'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [77]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 577)
X1 = cv.fit_transform(corpus).toarray()

In [78]:

y_predR = classifier3.predict(X1)

In [79]:
#******************* Showing demo results ********************

Sdataset = pd.read_csv('/content/test.csv', delimiter = ',')

In [80]:
final_op = {'test_ID' : Sdataset['test_id'] , 'description_x' : Sdataset['description_x'],'description_y': Sdataset['description_y'] ,'Same_Security' :y_predR}

In [84]:
# Load the true labels for the test dataset
Tdataset['Same_Security'] = y_predR
y_test_true = Tdataset['Same_Security'].values

# Calculate accuracy for random forest on test dataset
rf_test_accuracy = accuracy_score(y_test_true, y_predR)
print("Accuracy for Random Forest on Test Dataset: ", rf_test_accuracy)

Accuracy for Random Forest on Test Dataset:  1.0


In [85]:
final_op=pd.DataFrame(final_op)

In [86]:
print(final_op.iloc[0:10,:].values)


[[0 'semtech corp' 'semtech corporation' True]
 [1 'vanguard mid cap index' 'vanguard midcap index - a' True]
 [2 'spdr gold trust gold shares' 'spdr gold trust spdr gold shares' True]
 [3 'vanguard total bond index adm' 'vanguard total bond market index'
  True]
 [4 'oakmark international fund class i' 'oakmark international cl i'
  True]
 [5 'pfizer inc div: 1.200' 'pfizer inc com' True]
 [6 'spartan global ex us index fid adv cl' 'sptn glb xus idx adv' True]
 [7 'vanguard total bond market idx-adm'
  'vanguard total bond market index fund investor shares' True]
 [8 'banco latinoamericano de exportacio class e com stk npv'
  'banco latinoamericano come-e' True]
 [9 'baidu inc fadr 1 adr reps 0.1 ord shs'
  'baidu inc spons ads repr 0.10 ord cls a us0.00005' True]]
